POST https://node-boilerplate-o8oh.onrender.com/videos
Content-type: application/json

{
    "title": "video node",
    "duration":180,
    "description":"description"
}

###

GET https://node-boilerplate-o8oh.onrender.com/videos


###
PUT https://node-boilerplate-o8oh.onrender.com/video/aeaba082-4a41-4c08-b74f-b3922b74e1be
Content-type: application/json

{
    "title": "video 34",
    "duration":180,
    "description":"description"
}

###
DELETE https://node-boilerplate-o8oh.onrender.com/video/
