POST http://localhost:3333/videos
Content-type: application/json

{
    "title": "video node",
    "duration":180,
    "description":"description"
}

###

GET http://localhost:3333/videos


###
PUT http://localhost:3333/video/aeaba082-4a41-4c08-b74f-b3922b74e1be
Content-type: application/json

{
    "title": "video 34",
    "duration":180,
    "description":"description"
}

###
DELETE http://localhost:3333/video/
